In [1]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-8.2.0-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
Collecting protobuf<=4.21.12,>=4.21.1 (from mysql-connector-python)
  Using cached protobuf-4.21.12-cp310-abi3-win_amd64.whl (527 kB)
Using cached mysql_connector_python-8.2.0-cp310-cp310-win_amd64.whl (14.2 MB)
Installing collected packages: protobuf, mysql-connector-python
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.1
    Uninstalling protobuf-4.25.1:
      Successfully uninstalled protobuf-4.25.1
Successfully installed mysql-connector-python-8.2.0 protobuf-4.21.12

In [2]:
import mysql.connector
from mysql.connector import Error

Sobre una base de datos y para trabajar sobre ella, realizamos la conexión con el siguiente script donde se tienen en cuenta varios factores como el cursor, el commit, el tiempo de desconexion sin actividad (muy importante) y los errores:

In [4]:
#Conexión del ejemplo de Demetrio:
try:     
    connection = mysql.connector.connect(       
        host = "tú_ip_host",        
        user = "tú_usuario",        
        password = "tú_contraseña",        
        database = "nombre_base_de_dato",        
        connection_timeout = 180     
        )    
    if connection.is_connected():        
        db_Info = connection.get_server_info()        
        print("Todo Correcto", db_Info)        
        cursor = connection.cursor()        
        connection.commit()
except Error as e:    
    print("Error while connecting to MySQL", e)
finally:    
    if (connection.is_connected()):        
        connection.close()        
        print("MySQL connection is closed")

Todo Correcto 5.7.39-42-log
MySQL connection is closed

In [5]:
#Establecemos la conexión
connection = mysql.connector.connect(host = "tú_ip_host",        
        user = "tú_usuario",        
        password = "tú_contraseña",        
        database = "nombre_base_de_dato",        
        connection_timeout = 180)
#Conectamos el cursor, objeto importante para facilitar la ejecución de los comandos necesarios
cursor=connection.cursor()

Ejemplo de ejecucion de queries desde python en VSC:

In [29]:
querie1 = """ SELECT * FROM PRODUCTO; """
cursor.execute(querie1)
cursor.fetchall()

[('01', 'Hamburguesa', 2.6),
 ('02', 'Patatas', 2.0),
 ('03', 'tomate', 0.5),
 ('04', 'Queso', 1.0),
 ('05', 'Lechuga', 0.5),
 ('06', 'Pollo', 3.6),
 ('08', 'Bacon', 1.5),
 ('09', 'Coca cola', 3.0),
 ('10', 'Nestea', 3.0),
 ('11', 'Menú de Pollo', 5.0),
 ('12', 'Menú de Hamburguesa con queso', 6.0),
 ('13', 'Menú de Pollo con queso', 6.0),
 ('14', 'Menú de Hamburguesa', 6.0),
 ('15', 'Helado', 1.0),
 ('16', 'Tarta', 2.0),
 ('17', 'Fruta', 1.0),
 ('18', 'Agua', 2.0),
 ('19', 'Fanta', 3.0)]

In [30]:
import pandas as pd

De la consulta en SQL obtendremos un  Data Frame con pandas (podria ser un CSV o lo que quisieramos, recordar la función de read):

In [31]:
df1 = pd.read_sql(querie1, con= connection)
df1

C:\Users\Ariel\AppData\Local\Temp\ipykernel_1412\1777524237.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(querie1, con= connection)

   Codigo                         Nombre  Precio
0      01                    Hamburguesa     2.6
1      02                        Patatas     2.0
2      03                         tomate     0.5
3      04                          Queso     1.0
4      05                        Lechuga     0.5
5      06                          Pollo     3.6
6      08                          Bacon     1.5
7      09                      Coca cola     3.0
8      10                         Nestea     3.0
9      11                  Menú de Pollo     5.0
10     12  Menú de Hamburguesa con queso     6.0
11     13        Menú de Pollo con queso     6.0
12     14            Menú de Hamburguesa     6.0
13     15                         Helado     1.0
14     16                          Tarta     2.0
15     17                          Fruta     1.0
16     18                           Agua     2.0
17     19                          Fanta     3.0

Pasamos el data frame a csv y lo guardamos:

In [ ]:
df1.to_csv("frame_a_csv_con_pandas_importado_de_sql.csv", encoding= "latin1")

Configuramos para no tener limitaciones en lo que se muestra de la tabla:

In [32]:
pd.set_option("display.max_columns",None,"display.max_rows",None,"display.max_colwidth", None)

Ver toda la informacion de las tablas:

In [36]:
esquema = pd.read_sql("SELECT * FROM INFORMATION_SCHEMA.TABLES", con=connection)
esquema

C:\Users\Ariel\AppData\Local\Temp\ipykernel_1412\3408370883.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  esquema = pd.read_sql("SELECT * FROM INFORMATION_SCHEMA.TABLES", con=connection)

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ENGINE,VERSION,ROW_FORMAT,TABLE_ROWS,AVG_ROW_LENGTH,DATA_LENGTH,MAX_DATA_LENGTH,INDEX_LENGTH,DATA_FREE,AUTO_INCREMENT,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TABLE_COLLATION,CHECKSUM,CREATE_OPTIONS,TABLE_COMMENT
0,def,information_schema,CHARACTER_SETS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,384,0,32869632,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=87381,
1,def,information_schema,CLIENT_STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,362,0,33007160,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=92691,
2,def,information_schema,COLLATIONS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,231,0,33409761,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=145257,
3,def,information_schema,COLLATION_CHARACTER_SET_APPLICABILITY,SYSTEM VIEW,MEMORY,10,Fixed,NaN,195,0,32715540,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=172074,
4,def,information_schema,COLUMNS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=5578,
5,def,information_schema,COLUMN_PRIVILEGES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2565,0,33514290,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=13081,
6,def,information_schema,INDEX_STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1743,0,33533577,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=19250,
7,def,information_schema,ENGINES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,490,0,33148500,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=68478,
8,def,information_schema,EVENTS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=1236,
9,def,information_schema,FILES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,14498,0,33533874,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=2314,
10,def,information_schema,GLOBAL_STATUS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,3268,0,33513340,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=10267,
11,def,information_schema,GLOBAL_TEMPORARY_TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2168,0,33430560,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=15477,
12,def,information_schema,GLOBAL_VARIABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,3268,0,33513340,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=10267,
13,def,information_schema,KEY_COLUMN_USAGE,SYSTEM VIEW,MEMORY,10,Fixed,NaN,4637,0,33530147,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=7236,
14,def,information_schema,OPTIMIZER_TRACE,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=1157049,
15,def,information_schema,PARAMETERS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=12043,
16,def,information_schema,PARTITIONS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=11192,
17,def,information_schema,PLUGINS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=22656,
18,def,information_schema,PROCESSLIST,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=43351,
19,def,information_schema,PROFILING,SYSTEM VIEW,MEMORY,10,Fixed,NaN,308,0,33124168,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=108942,
20,def,information_schema,REFERENTIAL_CONSTRAINTS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,4814,0,33539138,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=6970,
21,def,information_schema,ROUTINES,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=1164,
22,def,information_schema,SCHEMATA,SYSTEM VIEW,MEMORY,10,Fixed,NaN,3464,0,33476096,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=9686,
23,def,information_schema,SCHEMA_PRIVILEGES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2179,0,33475977,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=15399,
24,def,information_schema,SESSION_STATUS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,3268,0,33513340,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=10267,
25,def,information_schema,SESSION_VARIABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,3268,0,33513340,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=10267,
26,def,information_schema,STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,5753,0,33511225,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=5832,
27,def,information_schema,TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,9471,0,33546282,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=3542,
28,def,information_schema,TABLESPACES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,6951,0,33545526,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=4827,
29,def,information_schema,TABLE_CONSTRAINTS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2504,0,33445928,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=13400,
30,def,information_schema,TABLE_PRIVILEGES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2372,0,33497384,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=14146,
31,def,information_schema,TABLE_STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1181,0,33468359,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=28411,
32,def,information_schema,TEMPORARY_TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2168,0,33430560,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=15477,
33,def,information_schema,THREAD_STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,177,0,32277897,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=189573,
34,def,information_schema,TRIGGERS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=1137,
35,def,information_schema,USER_PRIVILEGES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1986,0,33452184,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=16895,
36,def,information_schema,USER_STATISTICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,459,0,33192585,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=73103,
37,def,information_schema,VIEWS,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=13595,
38,def,information_schema,INNODB_CMP,SYSTEM VIEW,MEMORY,10,Fixed,NaN,25,0,26214400,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1342177,
39,def,information_schema,INNODB_CMP_RESET,SYSTEM VIEW,MEMORY,10,Fixed,NaN,25,0,26214400,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1342177,
40,def,information_schema,INNODB_SYS_DATAFILES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,12007,0,33547558,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=2794,
41,def,information_schema,XTRADB_READ_VIEW,SYSTEM VIEW,MEMORY,10,Fixed,NaN,166,0,33154848,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=202135,
42,def,information_schema,INNODB_SYS_TABLESTATS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1215,0,33526710,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=27616,
43,def,information_schema,XTRADB_RSEG,SYSTEM VIEW,MEMORY,10,Fixed,NaN,58,0,30408704,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=578524,
44,def,information_schema,INNODB_BUFFER_PAGE,SYSTEM VIEW,MEMORY,10,Fixed,NaN,6852,0,33533688,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=4897,
45,def,information_schema,INNODB_TRX,SYSTEM VIEW,MEMORY,10,Fixed,NaN,4536,0,33493824,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=7397,
46,def,information_schema,INNODB_CMP_PER_INDEX,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1755,0,33459075,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=19119,
47,def,information_schema,INNODB_METRICS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2994,0,33484896,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=11207,
48,def,information_schema,INNODB_FT_DELETED,SYSTEM VIEW,MEMORY,10,Fixed,NaN,9,0,18874368,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=3728270,
49,def,information_schema,INNODB_LOCKS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,31244,0,33524812,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1073,
50,def,information_schema,INNODB_LOCK_WAITS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,599,0,33498476,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=56017,
51,def,information_schema,XTRADB_INTERNAL_HASH_TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,327,0,33452100,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=102612,
52,def,information_schema,INNODB_TABLESPACES_ENCRYPTION,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2012,0,33487728,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=16677,
53,def,information_schema,INNODB_CMPMEM_RESET,SYSTEM VIEW,MEMORY,10,Fixed,NaN,29,0,30408704,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1157049,
54,def,information_schema,INNODB_SYS_FIELDS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,594,0,33218856,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=56488,
55,def,information_schema,XTRADB_ZIP_DICT,SYSTEM VIEW,InnoDB,10,Dynamic,NaN,0,16384,0,0,74448896,NaN,NaT,None,None,utf8_general_ci,None,max_rows=159025,
56,def,information_schema,INNODB_TABLESPACES_SCRUBBING,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2014,0,33521016,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=16660,
57,def,information_schema,INNODB_TEMP_TABLE_INFO,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1011,0,33389286,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=33189,
58,def,information_schema,INNODB_FT_INDEX_TABLE,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1054,0,33490850,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=31835,
59,def,information_schema,INNODB_CMPMEM,SYSTEM VIEW,MEMORY,10,Fixed,NaN,29,0,30408704,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1157049,
60,def,information_schema,INNODB_SYS_TABLESPACES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2133,0,33507297,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=15731,
61,def,information_schema,INNODB_CMP_PER_INDEX_RESET,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1755,0,33459075,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=19119,
62,def,information_schema,INNODB_SYS_FOREIGN_COLS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1748,0,33477696,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=19195,
63,def,information_schema,INNODB_FT_INDEX_CACHE,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1054,0,33490850,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=31835,
64,def,information_schema,INNODB_BUFFER_POOL_STATS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,257,0,32664700,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=130561,
65,def,information_schema,INNODB_FT_BEING_DELETED,SYSTEM VIEW,MEMORY,10,Fixed,NaN,9,0,18874368,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=3728270,
66,def,information_schema,INNODB_SYS_FOREIGN,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1752,0,33401880,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=19152,
67,def,information_schema,INNODB_BUFFER_PAGE_LRU,SYSTEM VIEW,MEMORY,10,Fixed,NaN,6669,0,33538401,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=5031,
68,def,information_schema,INNODB_FT_DEFAULT_STOPWORD,SYSTEM VIEW,MEMORY,10,Fixed,NaN,56,0,29360128,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=599186,
69,def,information_schema,INNODB_SYS_TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2091,0,33472728,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=16047,
70,def,information_schema,INNODB_SYS_COLUMNS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,610,0,33227310,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=55007,
71,def,information_schema,INNODB_FT_CONFIG,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1163,0,33410664,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=28851,
72,def,information_schema,XTRADB_ZIP_DICT_COLS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,25,0,26214400,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1342177,
73,def,information_schema,INNODB_SYS_INDEXES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,618,0,33231714,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=54295,
74,def,information_schema,INNODB_SYS_VIRTUAL,SYSTEM VIEW,MEMORY,10,Fixed,NaN,17,0,23767717,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1973790,
75,def,information_schema,INNODB_CHANGED_PAGES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,25,0,26214400,0,0,NaN,2023-12-17 16:18:31,None,None,utf8_general_ci,None,max_rows=1342177,
76,def,dbcetcfnoxjgwx,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,0,0,NaN,2023-03-03 17:23:34,None,None,utf8mb4_general_ci,None,,
77,def,dbcetcfnoxjgwx,Name,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,0,0,1.0,2023-03-03 18:04:19,None,None,utf8mb4_general_ci,None,,
78,def,dbcetcfnoxjgwx,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,49152,0,NaN,2023-03-03 17:23:34,None,None,utf8mb4_general_ci,None,,
79,def,dbcetcfnoxjgwx,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-03 17:23:35,None,None,utf8mb4_general_ci,None,,
80,def,dbcetcfnoxjgwx,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-03 17:23:34,None,None,utf8mb4_general_ci,None,,
81,def,dbcetcfnoxjgwx,RANKING_PRODUCTOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-03 17:23:35,None,None,utf8mb4_general_ci,None,,
82,def,dbcetcfnoxjgwx,REPARTIDOR,BASE TABLE,InnoDB,10,Dynamic,6.0,2730,16384,0,0,0,NaN,2023-03-03 17:23:34,None,None,utf8mb4_general_ci,None,,
83,def,dbcetcfnoxjgwx,alumno,BASE TABLE,InnoDB,10,Dynamic,4.0,4096,16384,0,0,0,5.0,2023-03-03 18:06:09,None,None,latin1_swedish_ci,None,,
84,def,dbcetcfnoxjgwx,asignatura,BASE TABLE,InnoDB,10,Dynamic,2.0,8192,16384,0,0,0,3.0,2023-03-03 18:06:06,None,None,latin1_swedish_ci,None,,
85,def,dbcetcfnoxjgwx,consta,BASE TABLE,InnoDB,10,Dynamic,28.0,585,16384,0,16384,0,NaN,2023-03-03 17:23:35,None,None,utf8mb4_general_ci,None,,
86,def,dbcetcfnoxjgwx,esta_compuesto,BASE TABLE,InnoDB,10,Dynamic,23.0,712,16384,0,16384,0,NaN,2023-03-03 17:23:35,None,None,utf8mb4_general_ci,None,,
87,def,dbcetcfnoxjgwx,labor_extra,BASE TABLE,InnoDB,10,Dynamic,2.0,8192,16384,0,16384,0,NaN,2023-03-03 18:06:07,None,None,latin1_swedish_ci,None,,
88,def,dbcetcfnoxjgwx,nota,BASE TABLE,InnoDB,10,Dynamic,8.0,2048,16384,0,32768,0,9.0,2023-03-03 18:06:07,None,None,latin1_swedish_ci,None,,
89,def,dbfggnhfh81wxm,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,0,0,NaN,2023-03-04 12:27:41,None,None,utf8_general_ci,None,,
90,def,dbfggnhfh81wxm,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,49152,0,NaN,2023-03-04 12:27:41,None,None,utf8_general_ci,None,,
91,def,dbfggnhfh81wxm,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-04 12:27:42,None,None,utf8_general_ci,None,,
92,def,dbfggnhfh81wxm,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-04 12:27:41,None,None,utf8_general_ci,None,,
93,def,dbfggnhfh81wxm,RANKING_PRODUCTOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-04 12:27:42,None,None,utf8_general_ci,None,,
94,def,dbfggnhfh81wxm,REPARTIDOR,BASE TABLE,InnoDB,10,Dynamic,6.0,2730,16384,0,0,0,NaN,2023-03-04 12:27:41,None,None,utf8_general_ci,None,,
95,def,dbfggnhfh81wxm,consta,BASE TABLE,InnoDB,10,Dynamic,28.0,585,16384,0,16384,0,NaN,2023-03-04 12:27:42,None,None,utf8_general_ci,None,,
96,def,dbfggnhfh81wxm,esta_compuesto,BASE TABLE,InnoDB,10,Dynamic,23.0,712,16384,0,16384,0,NaN,2023-03-04 12:27:42,None,None,utf8_general_ci,None,,
97,def,dbgdiwxw58a7hj,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,0,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
98,def,dbgdiwxw58a7hj,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,49152,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
99,def,dbgdiwxw58a7hj,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
100,def,dbgdiwxw58a7hj,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-04 11:29:01,None,None,utf8mb4_general_ci,None,,
101,def,dbgdiwxw58a7hj,RANKING_PRODUCTOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-04 11:29:03,None,None,utf8mb4_general_ci,None,,
102,def,dbgdiwxw58a7hj,REPARTIDOR,BASE TABLE,InnoDB,10,Dynamic,6.0,2730,16384,0,0,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
103,def,dbgdiwxw58a7hj,consta,BASE TABLE,InnoDB,10,Dynamic,28.0,585,16384,0,16384,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
104,def,dbgdiwxw58a7hj,esta_compuesto,BASE TABLE,InnoDB,10,Dynamic,23.0,712,16384,0,16384,0,NaN,2023-03-04 11:29:02,None,None,utf8mb4_general_ci,None,,
105,def,dbgsipp7ucsuwy,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,0,0,NaN,2023-03-03 13:30:46,None,None,utf8mb4_general_ci,None,,
106,def,dbgsipp7ucsuwy,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,49152,0,NaN,2023-03-03 13:30:47,None,None,utf8mb4_general_ci,None,,
107,def,dbgsipp7ucsuwy,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-03 13:30:47,None,None,utf8mb4_general_ci,None,,
108,def,dbgsipp7ucsuwy,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-03 13:30:46,None,None,utf8mb4_general_ci,None,,
109,def,dbgsipp7ucsuwy,RANKING_PRODUCTOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-03 13:30:48,None,None,utf8mb4_general_ci,None,,
110,def,dbgsipp7ucsuwy,REPARTIDOR,BASE TABLE,InnoDB,10,Dynamic,6.0,2730,16384,0,0,0,NaN,2023-03-03 13:30:47,None,None,utf8mb4_general_ci,None,,
111,def,dbgsipp7ucsuwy,consta,BASE TABLE,InnoDB,10,Dynamic,28.0,585,16384,0,16384,0,NaN,2023-03-03 13:30:47,None,None,utf8mb4_general_ci,None,,
112,def,dbgsipp7ucsuwy,esta_compuesto,BASE TABLE,InnoDB,10,Dynamic,23.0,712,16384,0,16384,0,NaN,2023-03-03 13:30:47,None,None,utf8mb4_general_ci,None,,
113,def,dbgsipp7ucsuwy,users,BASE TABLE,InnoDB,10,Dynamic,10.0,1638,16384,0,0,0,11.0,2023-03-03 18:19:02,None,None,utf8mb4_general_ci,None,,
114,def,dbibiqzwlobqu5,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,0,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
115,def,dbibiqzwlobqu5,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
116,def,dbibiqzwlobqu5,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
117,def,dbibiqzwlobqu5,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
118,def,dbibiqzwlobqu5,RANKING_PRODUCTOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
119,def,dbibiqzwlobqu5,REPARTIDOR,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,0,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
120,def,dbibiqzwlobqu5,consta,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,16384,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
121,def,dbibiqzwlobqu5,esta_compuesto,BASE TABLE,InnoDB,10,Dynamic,23.0,712,16384,0,16384,0,NaN,2023-03-02 06:34:00,None,None,utf8mb4_general_ci,None,,
122,def,dbqnzacyrqwmh0,EMPLEADO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,0,0,NaN,2023-03-03 13:45:05,None,None,utf8mb4_general_ci,None,,
123,def,dbqnzacyrqwmh0,PEDIDO,BASE TABLE,InnoDB,10,Dynamic,11.0,1489,16384,0,49152,0,NaN,2023-03-03 13:45:05,None,None,utf8mb4_general_ci,None,,
124,def,dbqnzacyrqwmh0,PEDIDOS_FINALIZADOS,BASE TABLE,InnoDB,10,Dynamic,0.0,0,16384,0,49152,0,NaN,2023-03-03 13:45:06,None,None,utf8mb4_general_ci,None,,
125,def,dbqnzacyrqwmh0,PRODUCTO,BASE TABLE,InnoDB,10,Dynamic,18.0,910,16384,0,16384,0,NaN,2023-03-03 13:45:05,None,None,utf8mb4_general_ci,None,,

Ver todas las tablas que tiene una base de datos:

In [39]:
tables = pd.read_sql("SHOW TABLES", con = connection)
tables

C:\Users\Ariel\AppData\Local\Temp\ipykernel_1412\245776354.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql("SHOW TABLES", con = connection)

  Tables_in_dbgsipp7ucsuwy
0                 EMPLEADO
1                   PEDIDO
2      PEDIDOS_FINALIZADOS
3                 PRODUCTO
4        RANKING_PRODUCTOS
5               REPARTIDOR
6                   consta
7           esta_compuesto
8                    users